instrument: 24
bpm : 120
rhythm :
  dividor : 4
  pattern : [
    [1,0,0,0,1,0,0,0],
    [1,0,0,0,1,0,0,0],
    [1,0,0,0,1,0,0,0],
    [1,0,0,0,1,0,0,0]
  ]
  order : cyclic
path: 
  pattern: ['G2', '`G2', 'G2', 'G2', 'G2', 'G2', 'G2', 'G2']
  order : cyclic
pitch:
  pattern: [
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [1,1,1,1,1,1,1,1],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0]
  ] 
  order: cyclic
amplitude:
  pattern : [0.6,0.5,0.6,0.5,0.6,0.5,0.6,0.5]
  order: cyclic
